Add Local Housing Allowance parameters
PolicyEngine/policyengine-uk pull request #787
Opened 2023-11-23 16:05 UTC by nikhilwoodruff

2023-11-25 15:51 UTC, MaxGhenis requested changes

2023-11-25 15:51 UTC, MaxGhenis commented on policyengine_uk/data/gov/brma_to_region.csv.gz
can you drop a README.md here showing how this was generated? (i'm guessing from the chatgpt mapping in #786)

also the source on the rents data

2023-11-25 15:51 UTC, MaxGhenis commented on policyengine_uk/tools/generate_brmas.py
this produces `data/gov/enhanced_frs_brmas.csv.gz`?

2023-11-26 13:14 UTC, nikhilwoodruff commented on policyengine_uk/tools/generate_brmas.py
Yes

2023-11-26 14:29 UTC, merged