Care to learn
PolicyEngine/policyengine-uk pull request #839
Opened 2024-03-20 22:30 UTC by Kittyaoooo

add care to learn variables

2024-04-25 14:10 UTC, nikhilwoodruff requested changes

2024-04-25 14:10 UTC, nikhilwoodruff commented on policyengine_uk/parameters/gov/dfe/care_to_learn.py
> +            return amount_per_child.IN_LONDON
I think this still returns the weekly amount, no?

2024-04-25 14:17 UTC, Kittyaoooo commented
I've multiplied the data in the amount_per_child.yaml to get monthly
amount, so the value returned should be monthly amount.

On Thu, Apr 25, 2024 at 10:10 AM Nikhil Woodruff ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In policyengine_uk/parameters/gov/dfe/care_to_learn.py
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PolicyEngine_policyengine-2Duk_pull_839-23discussion-5Fr1579548316&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=D4_TA5rySKIzQJTfuCZvuw&m=NU-naZdOMbfFKnxMKwTWxSkRDnya7lO1Hw4_C9t5zmPw95p8aG4N7K0LiLi-FE6L&s=SRAZJfgJGA77hH1hRegJeElieP40OpfKWDGogyPrzmo&e=>
> :
>
> >          if live_in_london:
> -            return amount_per_child.IN_LONDON # multiply to get monthly amount
> +            return amount_per_child.IN_LONDON
>
> I think this still returns the weekly amount, no?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PolicyEngine_policyengine-2Duk_pull_839-23pullrequestreview-2D2022633476&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=D4_TA5rySKIzQJTfuCZvuw&m=NU-naZdOMbfFKnxMKwTWxSkRDnya7lO1Hw4_C9t5zmPw95p8aG4N7K0LiLi-FE6L&s=OJokY1u7lXexg7BYfJ9UyiLcrqTMWnvYgo8h3LEoPGA&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AXIEG44ELR37J63NSWFVO33Y7EFFHAVCNFSM6AAAAABFALIPGKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMRSGYZTGNBXGY&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=D4_TA5rySKIzQJTfuCZvuw&m=NU-naZdOMbfFKnxMKwTWxSkRDnya7lO1Hw4_C9t5zmPw95p8aG4N7K0LiLi-FE6L&s=o5sMTkdrTzvXDewOmPZ8aWZlJa2sZHDDVTBqG6C8B10&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-02 14:59 UTC, nikhilwoodruff commented
@Kittyaoooo- sorry, we do need to multiply within the formula. This is because when we add references, they need to match the value in the parameter file, and if we've manually changed it to be monthly, it won't match.

2024-05-02 15:00 UTC, nikhilwoodruff commented on policyengine_uk/parameters/gov/dfe/care_to_learn.py
This python file should be with the others in the variables/ folder.

2024-05-02 15:01 UTC, nikhilwoodruff commented on policyengine_uk/tests/policy/baseline/gov/hmrc/income_tax/allowances/allowance_integration.yaml
These files are from an earlier PR- could you remove them? I'm not sure why they're here.

2024-05-10 22:11 UTC, closed without merging